### PR TITLE
add UUID

### PR DESCRIPTION
**Pull request by klyse**
Hi Matthew,

I added the UUID device number to your solution. I hope i didn't break anything.

Klaus

### CODE REVIEW

**Comment by MatthewKing** [comment]
Hi. This looks pretty good. I'm super busy with a newborn baby and some other challenges in my personal life, so it may take me a few days/weeks to get around to reviewing and releasing this change into the main DeviceId package on NuGet. Thanks for your patience and understanding.

**Comment by klyse** [comment]
sure, let me know if I should change something. Congratulations to the newborn ;).

**Comment by klyse** [comment]
Hi, @MatthewKing  any updates? :)

**Comment by MatthewKing** [comment]
Thanks for the reminder. I've merged the PR and will be releasing a new version soon. Cheers!

**Pull request merged**
