### PR TITLE
Reduced WmiDeviceIdComponent query time 

### PR DESCRIPTION
**Pull request by Zaczero**
Previously the `WmiDeviceIdComponent` queried all properties from the class which takes quite a long time. Now it only queries one property specified by `_wmiProperty` which makes the whole process near-instant :- ).

Additionally, updated `.gitignore` with the latest [Visual Studio version](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) so it's compatible with various VS extensions.

### CODE REVIEW

**Comment by MatthewKing** [comment]
This looks great, thanks. Give me a couple of days to review properly and merge. Cheers!

**Comment by MatthewKing** [comment]
Would you mind removing the .gitignore changes? Should be good to merge after that. Thanks!

**Comment by Zaczero** [comment]
> 
> 
> Would you mind removing the .gitignore changes? Should be good to merge after that. Thanks!

welp sure

**Comment by MatthewKing** [comment]
Thanks mate, much appreciated! Will get this merged and released as soon as I get a sec. Cheers

**Comment by Zaczero** [comment]
What's the reason behind such a basic .gitignore if I may ask?

**Comment by MatthewKing** [comment]
I'm just a weirdo I guess 😄

**Pull request merged**
